image: #moshedayan/gitpod:latest
  file: .gitpod.Dockerfile

tasks:
  - name: zsh
    env:
      EDITOR: vim
      AWS_PROFILE: private
      SHELL: zsh
    command: exec zsh 
    # init: bash ~/.config/setup.sh