image: #moshedayan/gitpod:latest
  file: .gitpod.Dockerfile

tasks:
  - name: fish
    env:
      EDITOR: nvim
      AWS_PROFILE: private
      SHELL: fish
    command: exec fish 
    # init: bash ~/.config/setup.sh