image: gitpod/workspace-base:latest
  # file: .gitpod.Dockerfile

tasks:
  - name: fish
    env:
      EDITOR: nvim
      AWS_PROFILE: private
      SHELL: fish
    command: /usr/bin/fish 
    # init: bash ~/.config/setup.sh