image: moshedayan/gitpod:latest
  # file: Dockerfile

tasks:
  - name: tmux
    command: /usr/bin/tmux -f /home/gitpod/.dotfiles/tmux/tmux.conf
    env:
      EDITOR: vim
      AWS_PROFILE: private
  - name: fish
    command: /usr/bin/fish
    env:
      EDITOR: vim
      AWS_PROFILE: private